### ISSUE TITLE
Finalize release procedure from staging to prod (Create CD workflows for deploying to staging new changes)

### ISSUE THREAD

**Issue by Pasarus** [fiaisis/gitops#1]
Make is so that when you move a release tag, a series of git patches are applied to the staging branch, then the contents of that staging branch are pushed to the production branch.

Example github actions workflow that may work:
```yml
name: Apply patches and push to production
on:
  push:
    tags:
      - 'release'
jobs:
  apply-patches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Apply patches
        run: |
          for patch in path/to/patches/*.patch; do
            git apply $patch
          done
      - name: Push to production branch
        run: |
          git checkout -b production
          git push origin production
```
