### ISSUE TITLE
Re-evaluate monitoring stack

### ISSUE THREAD

**Issue by Pasarus** [fiaisis/gitops#76]
The monitoring stack currently consists of self-managed and self-deployed versions of the following:
- Grafana (Self hosted) - Management
- Prometheus (Metrics) - Prod
- Promtail (Logs) - Prod

Should it look like this:
- Grafana (Self hosted) - Management
- Grafana Alloy (Deploys other things and provides a pipeline for how we handle the logs) - Management/Prod/Messaging
  - Prometheus (Metrics) - Management/Prod/Messaging
  - OpenTelemetry (Traces) - Prod
  - Pyroscope (Profiling) - Prod
  - Promtail (Logs) - Prod
  - Beyla (eBPF auto instrumentation) - Prod

Will notably need to reimplement the service monitor for RabbitMQ for use with Prometheus:
```yaml
---
# This file is from here and redistributed under the Mozilla Public License 2.0: https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-servicemonitor.yml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rabbitmq
  # If labels are defined in spec.serviceMonitorSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
spec:
  endpoints:
  - port: prometheus
    scheme: http
    interval: 15s
    scrapeTimeout: 14s
  - port: prometheus-tls
    scheme: https
    interval: 15s
    scrapeTimeout: 14s
    tlsConfig:
      insecureSkipVerify: true # set to false and uncomment lines below to enable tls verification
        # ca:
        #   secret:
        #     key: ca.crt
        #     name: tls-secret # name of the secret containing the CA cert which signed the RabbitMQ Prometheus TLS cert
        # serverName: '*.RABBITMQ-INSTANCE-NAME.NAMESPACE.svc.cluster.local'
  - port: prometheus
    scheme: http
    path: /metrics/detailed
    params:
      family:
        - queue_coarse_metrics
        - queue_metrics
    interval: 15s
    scrapeTimeout: 14s
  - port: prometheus-tls
    scheme: https
    path: /metrics/detailed
    params:
      family:
        - queue_coarse_metrics
        - queue_metrics
    interval: 15s
    scrapeTimeout: 14s
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq
  namespaceSelector:
    any: true
---
# This file is from here and redistributed under the Mozilla Public License 2.0: https://raw.githubusercontent.com/rabbitmq/cluster-operator/main/observability/prometheus/monitors/rabbitmq-cluster-operator-podmonitor.yml
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rabbitmq-cluster-operator
  # If labels are defined in spec.podMonitorSelector.matchLabels of your deployed Prometheus object, make sure to include them here.
spec:
  podMetricsEndpoints:
  - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: rabbitmq-operator
  namespaceSelector:
    matchNames:
    - rabbitmq-system
```
